$script_mysql = <<-SCRIPT
apt-get update && \
apt-get install - y mysql-server-5.7 && \
mysql -e "create user 'phpuser'@'%' identified by 'pass';"
date > /etc/vagrant_provisioned_at
SCRIPT


Vagrant.configure("2") do |config|
	config.vm.box = "ubuntu/bionic64"
	config.vm.network "forwarded_port", guest: 80, host: 8089
	config.vm.network "public_network", ip: "10.0.0.150"

	config.vm.provision "shell",
		inline: "cat /config/id_bionic.pub >> .ssh/authorized_keys"
	config.vm.provision "shell", inline: $script_mysql
	config.vm.provision "shell",
        inline: "cat /configs/mysqld.cnf > /etc/mysql/mysql.conf.d/mysqld.cnf"
    config.vm.provision "shell",
        inline: "service mysql restart"

	config.vm.synced_folder "./configs", "/configs"
	config.vm.synced_folder ".", "/vagrant", disabled: true
end
#sudo mysql 
#select user from mysql.user
#/etc/mysql/mysql.conf.d/mysqld.cnf que possui o IP bind-address = 127
