$script_mysql = <<-SCRIPT
apt-get update && \
apt-get install -y mysql-server-5.7 && \
mysql -e "create user 'phpuser'@'%' identified by 'pass';"
date > /etc/vagrant_provisioned_at
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  config.vm.define "mysqldb" do |mysql| 
	mysql.vm.network "public_network", ip: "10.0.0.5"

	mysql.vm.provision "shell",
	 inline: "cat /configs/id_vangrant.pub >> .ssh/authorized_keys"
	mysql.vm.provision "shell", inline: $script_mysql
	mysql.vm.provision "shell",
	 inline: "cat /configs/mysqld.cnf > /etc/mysql/mysql.conf.d/mysqld.cnf"
	mysql.vm.provision "shell",	inline: "service mysql restart"

	mysql.vm.synced_folder "./configs", "/configs"
	mysql.vm.synced_folder ".", "/vagrant", disabled: true
  end

  config.vm.define "phpweb" do |phpweb|
	phpweb.vm.network "forwarded_port", guest: 80, host: 8888
	phpweb.vm.network "public_network", ip: "10.0.0.6",
	auto_correct: true

	phpweb.vm.synced_folder "./configs", "/configs"
	phpweb.vm.synced_folder ".", "/vagrant", disabled: true
	phpweb.vm.provision "shell",
	 inline: "cat /configs/id_vangrant.pub >> .ssh/authorized_keys"

	phpweb.vm.provision "shell", 
	inline: "apt-get update && apt-get install -y puppet"
	 
	phpweb.vm.provision "puppet" do |puppet|
		puppet.manifests_path = "./configs/manifests"
		puppet.manifest_file = "phpweb.pp"
	  end
  end	
  config.vm.define "mysqlserver" do |mysqlserver|
	mysqlserver.vm.network "public_network", ip: "10.0.0.7"
	mysqlserver.vm.provision "shell",
	inline: "cat /vagrant/configs/id_vangrant.pub >> .ssh/authorized_keys"
  end

  config.vm.define "ansible" do |ansible|
	ansible.vm.network "public_network", ip: "10.0.0.8"

	ansible.vm.provision "shell",
	 inline: "cp /vagrant/configs/id_vangrant  /home/vagrant && \
	 chmod 600 /home/vagrant/id_vangrant && \
	 chwon vagrant:vagrant /home/vagrant/id_vagrant" 
		
	ansible.vm.provision "shell",
		inline: "apt-get update && \
				 apt-get install -y software-properties-common && \
				 apt-add-repository --yes --update ppa:ansible/ansible && \
				 apt-get install -y ansible"
end
end

